### ISSUE TITLE
Error: Cannot call method 'map' of undefined

### ISSUE THREAD

**Issue by kenwarner** [reharik/grunt_xunit_runner#2]
Hi there, the 0.1.7 release seems to have a bug in it, I'm getting this error message

Error: Cannot call method 'map' of undefined

**Comment by reharik** [comment]
Hey, can you send me the grunt task you are using so I can debug this
please?
Thanks,
R

**Comment by kenwarner** [comment]
Thanks, this is the config

xunit_runner: {
			options: {
				xUnit: '.\\node_modules\\grunt-xunit\\vendor\\xunit\\xunit.console.exe', // in the grunt-xunit package, not grunt-xunit-runner
				silent: true,
				teamcity: true
			},
			files: {
				src: [
					'Foo/bin/**/Foo.Tests.dll',
					'Bar/bin/**/Bar.Tests.dll'
				]
			}
		},

**Comment by reharik** [comment]
please try that v 0.1.8
sorry.

**Comment by kenwarner** [comment]
looks good here. thanks a lot for the quick fix (and the project in general too)!!
